sudo: required
services:
  - docker

before_install:
  - docker build -t devzons/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devzons/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-west-1-309356939300'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
